### ISSUE TITLE
Logging/debugging instructions with VS Code

### ISSUE THREAD

**Issue by donaldpipowitch** [RyanCavanaugh/sample-ts-plugin#4]
Hi 👋

I try to create a TypeScript plugin and followed most of your instructions, but it looks like the plugin isn't really used. So some questions:

1. Should I see an error somewhere, if I misconfigured the `plugins` setting? (I can't see an error from the language server inside VS Code or inline inside the `tsconfig.json`.
2. If the plugin loads correctly, should I see my logging in the `Output` pane of VS Code, if I set `"typescript.tsserver.trace": "verbose"` in my workspace settings?
3. Can `name` of an plugin be a path as well (either absolute or relative) or refer to a file inside a package (e.g. `cool-lib/ts-plugin`) or is it the `name` of the package and the TypeScript plugin _must_ be the `main` file?

Thank you :)

**Comment by donaldpipowitch** [comment]
Ah, I just saw that this is a more up-to-date documentation based on this repo which partially answers my questions: https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin/_compare/df3df23d562cfeebd14e218aeba60f7be9e00725...f7738c78efe4e7f48a03edf5163b75b95408a65c#diff-337c3faf82552102609c27b3fd184f4fR79.

Maybe we can point out in the README that the more recent document can be found at https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin.

**Comment by donaldpipowitch** [comment]
Looks like I can't even get this example to run :/

**What I did**
- Cloned
- build
- moved into a sample project with updated `tsconfig.json`

**What happens**
- ~no log output~ _ah_ you need to select `TypeScript` in the output pane, but still no output which indicates if my or this plugin loads (or fails to load)
- `(new Date()).g;` still shows `getDate` as a completion

TypeScript 2.6.2/2.7.0-dev, VS Code 1.19.1

**Comment by RyanCavanaugh** [comment]
Thanks for trying this! Sorry to hear you're running into debugging difficulties; figuring out a null result is always annoying.

1. Unfortunately we don't currently surface failed plugin loads as there's no editor-agnostic mechanism for delivering "one-time" failure messages. If you simply wrote the plugin configuration *syntactically* wrong, you'd see an error in the tsconfig.json, though
2. I'm not sure how this gets populated -- for writing a plugin you'll want to enable tsserver logging, see https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#advanced-topics
3. This is basically an NPM module name, so it can be something like path/to/the/subfolder. This is resolved the same way we resolve node module names

Here's some sample tsserver log output and how I obtained it so you can see what you're looking for in tsserver's log file

### Plugin load failure
In an empty folder: `tsc --init`, `npm init -y`, `npm link sample-ts-plugin`, replace `tsconfig.json` with 
```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "plugins": [{
            "name": "sample-ts-plugin",
            "remove": ["caller", "callee", "getDay"]
        }]
    }
}
```
Then open in VS Code.

Log output
```
Info 14   [12:28:7.771] Opened configuration file c:/Throwaway/plugintest/tsconfig.json
Info 15   [12:28:7.777] Enabling plugin sample-ts-plugin from candidate paths: C:/github/TypeScript/built/local/tsserver.js/../../..
Info 16   [12:28:7.778] Loading sample-ts-plugin from C:/github/TypeScript/built/local/tsserver.js/../../.. (resolved to C:/github/TypeScript/node_modules)
Info 17   [12:28:7.800] Failed to load module 'sample-ts-plugin': Error: Could not resolve JS module 'sample-ts-plugin' starting at 'C:/github/TypeScript/node_modules'. Looked in: C:/github/TypeScript/node_modules/sample-ts-plugin/package.json, C:/github/TypeScript/node_modules/sample-ts-plugin.js, C:/github/TypeScript/node_modules/sample-ts-plugin.jsx, C:/github/TypeScript/node_modules/sample-ts-plugin/index.js, C:/github/TypeScript/node_modules/sample-ts-plugin/index.jsx, C:/github/node_modules/sample-ts-plugin/package.json, C:/github/node_modules/sample-ts-plugin.js, C:/github/node_modules/sample-ts-plugin.jsx, C:/github/node_modules/sample-ts-plugin/index.js, C:/github/node_modules/sample-ts-plugin/index.jsx, C:/node_modules/sample-ts-plugin/package.json, C:/node_modules/sample-ts-plugin.js, C:/node_modules/sample-ts-plugin.jsx, C:/node_modules/sample-ts-plugin/index.js, C:/node_modules/sample-ts-plugin/index.jsx
    at Object.resolveJavaScriptModule (C:\github\TypeScript\built\local\tsserver.js:6405:19)
    at Object.sys.require (C:\github\TypeScript\built\local\tsserver.js:108390:45)
    at Function.Project.resolveModule (C:\github\TypeScript\built\local\tsserver.js:101998:35)
    at ConfiguredProject.enablePlugin (C:\github\TypeScript\built\local\tsserver.js:102862:50)
    at ConfiguredProject.enablePlugins (C:\github\TypeScript\built\local\tsserver.js:102831:30)
    at new ConfiguredProject (C:\github\TypeScript\built\local\tsserver.js:102785:23)
    at ProjectService.createConfiguredProject (C:\github\TypeScript\built\local\tsserver.js:104232:31)
    at ProjectService.openClientFileWithNormalizedPath (C:\github\TypeScript\built\local\tsserver.js:104674:44)
    at IOSession.Session.openClientFile (C:\github\TypeScript\built\local\tsserver.js:106163:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\github\TypeScript\built\local\tsserver.js:105369:31)
    at C:\github\TypeScript\built\local\tsserver.js:106822:88
    at IOSession.Session.executeWithRequestId (C:\github\TypeScript\built\local\tsserver.js:106813:28)
    at IOSession.Session.executeCommand (C:\github\TypeScript\built\local\tsserver.js:106822:33)
    at IOSession.Session.onMessage (C:\github\TypeScript\built\local\tsserver.js:106842:35)
    at Interface.<anonymous> (C:\github\TypeScript\built\local\tsserver.js:108103:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
Info 18   [12:28:7.800] Couldn't find sample-ts-plugin
```

### Successful load

VS Code can only use plugins which originate "next to" the TypeScript install. So in the same folder, `npm install typescript`. Select "use workspace version" in VS Code's TS version selector. New output:
```
Info 13   [12:31:58.164] For info: c:/Throwaway/plugintest/a.ts :: Config file name: c:/Throwaway/plugintest/tsconfig.json
Info 14   [12:31:58.184] Opened configuration file c:/Throwaway/plugintest/tsconfig.json
Info 15   [12:31:58.231] Enabling plugin sample-ts-plugin from candidate paths: c:/Throwaway/plugintest/node_modules/typescript/lib/tsserver.js/../../..
Info 16   [12:31:58.231] Loading sample-ts-plugin from c:/Throwaway/plugintest/node_modules/typescript/lib/tsserver.js/../../.. (resolved to c:/Throwaway/plugintest/node_modules/node_modules)
Info 17   [12:31:58.242] This message will appear in your logfile if the plugin loaded correctly
Info 18   [12:31:58.242] Plugin validation succeded
Info 19   [12:31:58.243] FileWatcher:: Added: PathInfo: c:/Throwaway/plugintest/tsconfig.json Project: c:/Throwaway/plugintest/tsconfig.json WatchType: Config file for the program
```
![image](https://user-images.githubusercontent.com/6685088/34741922-338cae10-f539-11e7-8c7c-1f481f0b17c7.png)

Let me know how else I can help

**Comment by donaldpipowitch** [comment]
1. **Thank you!**
2. It looks like VS Codes `typescript.tsserver.trace` setting is definitely a different output. I _finally_ got some output logging output. It looks like is misconfigured `-file` the whole time (it needs to be a absolute file path I guess... and maybe `~` is not allowed. I now use this handy one-liner to get logging and open my project in the same directory: `$ export TSS_LOG="-level verbose -file $PWD/tss.log" && code .`. (Probably obvious to others, but it took me some time to find my misconfigured `-file` param.)
3. God, I'm dumb. I configured to remove `getDay` and saw `getDate` and misread it as `getDay` the whole time... 🤦‍♀️

On a total different note... I saw https://tsconf.io/ and wondered if plugin authoring (maybe for a better integration between TypeScript and WebPack loaders) could be a nice topic. (Even for a first time speaker. Do you know if tsconf.io takes care of traveling costs for speakers?) Sorry, if you're not the right person for this to ask 😅  I'm just happy I can go on writing my first plugin and tsconf was one of the reasons which motivated me again 😀
